FORMAT: 1A
HOST: https://api.wheely.com

# API Blueprint API

Спецификация API


## Order [/orders/{id}]

+ Parameters

    + id: 5b83bd33c06e3100060000c8 (string) - ID заказа который требуется получить.

### Получение записи [GET]

+ Response 200 (application/json)

    + Attributes

        + data
            + id: 5b83bd33c06e3100060000c8 (string, required) - Уникальный монговский идентификатор заказа
            + type: orders (string, required)
            + attributes (Order Model)
            + relationships (object)

                + city
                    + data
                        + type: cities
                        + id: 5b83bd33c06e3100060000c8
                    + links
                        + self: https://foo/

                + user
                    + data
                        + type: users
                        + id: 5b83bd33c06e3100060000c8
                    + links
                        + self: https://foo/

                + payment_method
                    + data
                        + type: payment_methods
                        + id: 5b83bd33c06e3100060000c8
                    + links
                        + self: https://foo/

                + service
                    + data
                        + type: services
                        + id: 5b83bd33c06e3100060000c8
                    + links
                        + self: https://foo/

                + car
                    + data
                        + type: cars
                        + id: 5b83bd33c06e3100060000c8
                    + links
                        + self: https://foo/

                + payment_methods
                    + data (array)
                    + links
                        + self: https://foo/


+ Response 400 (application/json)

    + Attributes

        + errors
            + code: 100 (number, required) - Внутренний код ошибки.
            + status: 400 (string)
            + source (object, required)
                + pointer: /data (string)
            + title: pay failed (string)

+ Response 400 (application/json)

    + Attributes

        + errors
            + code: 200 (number, required) - Внутренний код ошибки.
            + status: 400 (string)
            + source (object, required)
                + pointer: /data (string)
            + title: pay failed (string)

+ Response 500 (application/json)

        Something went wrong

## City [/cities/{id}]

+ Parameters

    + id: 5b83bd33c06e3100060000c8 (string) - ID города который требуется получить.

### Получение записи [GET]

+ Response 200 (application/json)

    + Attributes

        + data
            + id: 5b83bd33c06e3100060000c8 (string, required) - Уникальный монговский идентификатор
            + type: cities (string, required)
            + attributes (City Model)
            + relationships


+ Response 400 (application/json)

    + Attributes

        + errors
            + code: 777 (number, required) - Внутренний код ошибки.
            + status: 400 (string)
            + source (object, required)
                + pointer: /data (string)
            + title: pay failed (string) - Короткий, человеко-читаемый текст ошибки (может быть локализован).

## User [/users/{id}]

+ Parameters

    + id: 5b83bd33c06e3100060000c8 (string) - ID города который требуется получить.

### Получение записи [GET]

+ Response 200 (application/json)

    + Attributes

        + data
            + id: 5b83bd33c06e3100060000c8 (string, required) - Уникальный монговский идентификатор
            + type: users (string, required)
            + attributes (User Model)
            + relationships


+ Response 400 (application/json)

    + Attributes

        + errors
            + code: 777 (number, required) - Внутренний код ошибки.
            + status: 400 (string)
            + source (object, required)
                + pointer: /data (string)
            + title: pay failed (string) - Короткий, человеко-читаемый текст ошибки (может быть локализован).

## Service [/services/{id}]

+ Parameters

    + id: 5b83bd33c06e3100060000c8 (string) - ID города который требуется получить.

### Получение записи [GET]

+ Response 200 (application/json)

    + Attributes

        + data
            + id: 5b83bd33c06e3100060000c8 (string, required) - Уникальный монговский идентификатор
            + type: services (string, required)
            + attributes (Service Model)
            + relationships


+ Response 400 (application/json)

    + Attributes

        + errors
            + code: 777 (number, required) - Внутренний код ошибки.
            + status: 400 (string)
            + source (object, required)
                + pointer: /data (string)
            + title: pay failed (string) - Короткий, человеко-читаемый текст ошибки (может быть локализован).

## Car [/cars/{id}]

+ Parameters

    + id: 5b83bd33c06e3100060000c8 (string) - ID города который требуется получить.

### Получение записи [GET]

+ Response 200 (application/json)

    + Attributes

        + data
            + id: 5b83bd33c06e3100060000c8 (string, required) - Уникальный монговский идентификатор
            + type: cars (string, required)
            + attributes (Car Model)
            + relationships


+ Response 400 (application/json)

    + Attributes

        + errors
            + code: 777 (number, required) - Внутренний код ошибки.
            + status: 400 (string)
            + source (object, required)
                + pointer: /data (string)
            + title: pay failed (string) - Короткий, человеко-читаемый текст ошибки (может быть локализован).

## Exchange Type [/exchange-types]

### Получение списка типов [GET]

+ Response 200 (application/json)

    + Attributes

        + slug: diadoc (string, required) - Уникальное имя способа обмена документами латиницей
        + names (array)


# Data Structures

## Translated String Definition (object)

+ translation: Москва (string, required)
+ locale (enum, required)
    + Default: ru
    + Members
        + ru
        + en

## Geo Position Definition (object)

+ lat: 55.753215 (number, required)
+ lng: 37.622504 (number, required)

## Order Model (object)

+ number: 2752935 (number, required) - Уникальный человекопонятный идентификатор заказа
+ status (enum, required)
    + Default: done
    + Members
        + new
        + accepted
        + scheduled
        + looking_for_drivers
        + car_not_found
        + on_the_way
        + arrived
        + serving
        + done
        + failed
        + cancelled
        + no_show
+ events (array[Order Event Model], required)
+ paid (boolean, required)
+ price (number)
+ currency: RUB (string)
+ price_details (array[Order Price Detail Model], required)
+ pickup_at (number)
+ pickup (number, required)
+ dropoff (number)
+ real_dropoff (number)
+ created_at (number, required) - Дата создания заказа в БД
+ updated_at (number, required) - Дата изменения заказа в БД

## Order Event Model (object)

+ name: done (enum, required)
    + Members
      + new
      + accepted
      + scheduled
      + looking_for_drivers
      + car_not_found
      + on_the_way
      + arrived
      + serving
      + done
      + failed
      + cancelled
      + no_show
      + extrastop
+ timestamp: 1539182736134 (number, required)

## Order Price Detail Model (object)

+ type: distance (string, required)
+ price: 1000 (number, required)
+ value: 10 (number, optional)
+ unit: km (enum, optional)
    + Members
      + km
      + mile
      + minute
      + second
+ unit_price: 100 (number, optional)
+ service: true (boolean, required)

## City Model (object)

+ slug: moscow (string, required)
+ name (Translated String Definition, required)
+ center (Geo Position Definition, required)
+ radius: 100 (string, required)
+ timezone: 180 (string, required)
+ currency: RUB (string, required)

## User Model (object)

+ slug: moscow (string, required)

## Service Model (object)

+ slug: moscow (string, required)

## Car Model (object)

+ license_plate: A000AA777 (string, required)
